version: '3'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
     - 80:80
     - 443:443

    volumes:
      - './src:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'

  node:
    image: node:latest

    working_dir: '/usr/share'
    ports:
     - 8080:8080

    volumes:
      - './src/import-map-server-delayed.js:/usr/share/index.js'
      - './src/import-map.json:/usr/share/import-map.json'

    command: node index.js


  consul:
    image: consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'

    volumes:
      - './consul.json:/consul/config/consul.json'
networks:
  default:
